AllCops:
  Exclude:
    - 'db/schema.rb'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Layout/IndentArray:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 50

Metrics/BlockLength:
  Max: 160

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 80

Metrics/PerceivedComplexity:
  Max: 20

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassAndModuleChildren:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

# inherit_from: .rubocop_todo.yml
