Layout/FirstParameterIndentation:
  EnforcedStyle: consistent

Metrics/LineLength:
  Max: 100

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

inherit_from: .rubocop_todo.yml
