language: ruby
cache: bundler
addons:
  code_climate:
    repo_token: aaac6425dc45e7af413ba245b019fc76b5a7802cbb793c37eac4a42e779a11a6
rvm:
- 2.4.0
script: bundle exec rspec
after_success:
  - bundle exec codeclimate-test-reporter
env:
  global:
    - TWILIO_PHONE_NUMBER=+14155555555
    - APP_DOMAIN=localhost
