development:
  url: <%= ENV['DATABASE_URL'] %>
  database: 'casecompanion-development'

test:
  url: <%= ENV['DATABASE_URL'] %>
  database: 'casecompanion-test'

# Note: This file is replaced in production by the Capistrano deploy.
production:
  url: <%= ENV['DATABASE_URL'] %>
