DROP TABLE CFA_TOM_VRN;
DROP TABLE CFA_TOM_PROBATION;
DROP TABLE CFA_TOM_RESTITUTION;
DROP TABLE CFA_TOM_VICTIM_INFO;
DROP TABLE CFA_TOM_DEFENDANT_INFO;

-- TODO: These queries will all run faster with the following indices:
-- CREATE INDEX cfa_tom_case_person ON CASE_PERSON (CASE_ID_NBR, CASE_PERSON_TYPE, PERSON_ID_NBR);
-- CREATE INDEX cfa_tom_cp_address ON CASE_PERSON_ADDRESS (PERSON_ID_NBR, SUB_ONLY, ALL_DOCS) WITH DROP_EXISTING;
-- CREATE INDEX cfa_tom_cp_phone ON CASE_PERSON_PHONE (PERSON_ID_NBR, DEFAULT_PHONE) WITH DROP_EXISTING;
-- CREATE INDEX cfa_tom_cp_info ON CASE_PERSON_INFO (PERSON_ID_NBR);
