-- Find all recently-updated Victims or Victim-Witnesses and store their IDs in
-- a table to simplify other queries.
SELECT CASE_ID_NBR, PERSON_ID_NBR
INTO CFA_TOM_VRN
FROM CASE_PERSON
WHERE (UPDATE_DATE BETWEEN DATEADD(month, -2, GETDATE()) AND GETDATE())
AND (CASE_PERSON_TYPE = 'VICTIM' OR CASE_PERSON_TYPE = 'VIC/WIT');

-- Find all recently-updated probation sentences.
SELECT     CASE_CHARGE.CASE_ID_NBR, CASE_CHARGE.PERSON_ID_NBR AS OFFENDER_PERSON_ID_NBR, PROBATION.PROBATION_ID_NBR,
                      CASE_CHARGE.CHARGE_STATE, CHARGE_SENTENCE.SENTENCE_ID_NBR, CASE_CHARGE.CASE_ID_NBR AS Expr1,
                      CASE_CHARGE.CHARGE_ID_NBR, CASE_CHARGE.CHARGE_STATE AS Expr2, PROBATION.TOTAL_PROB_QTY,
                      PROBATION.TOTAL_PROB_QTY_UNIT
INFO CFA_TOM_PROBATION
FROM         PROBATION INNER JOIN
                      CHARGE_SENTENCE ON PROBATION.SENTENCE_ID_NBR = CHARGE_SENTENCE.SENTENCE_ID_NBR INNER JOIN
                      CASE_CHARGE ON CHARGE_SENTENCE.CHARGE_ID_NBR = CASE_CHARGE.CHARGE_ID_NBR
WHERE     (PROBATION.UPDATE_DATE BETWEEN DATEADD(month, - 2, GETDATE()) AND GETDATE()) AND (CASE_CHARGE.CHARGE_STATE = 'CONVICTED') AND
                      (PROBATION.TOTAL_PROB_QTY IS NOT NULL)


-- Find all recently-updated restitution sentences.
SELECT     RESTITUTION_RECIPIENT.CASE_ID_NBR, RESTITUTION_RECIPIENT.PERSON_ID_NBR AS VICTIM_PERSON_ID_NBR,
                      CHARGE_SENTENCE.PERSON_ID_NBR AS OFFENDER_PERSON_ID_NBR, SENTENCE_RESTITUTION.AMOUNT,
                      SENTENCE_RESTITUTION.RESTITUTION_TYPE, SENTENCE_RESTITUTION.UPDATE_DATE
INTO            CFA_TOM_RESTITUTION
FROM         SENTENCE_RESTITUTION INNER JOIN
                      RESTITUTION_RECIPIENT ON SENTENCE_RESTITUTION.RECIPIENT_ID_NBR = RESTITUTION_RECIPIENT.RECIPIENT_ID_NBR INNER JOIN
                      CHARGE_SENTENCE ON SENTENCE_RESTITUTION.SENTENCE_ID_NBR = CHARGE_SENTENCE.SENTENCE_ID_NBR INNER JOIN
                      CASE_CHARGE ON CHARGE_SENTENCE.CHARGE_ID_NBR = CASE_CHARGE.CHARGE_ID_NBR
WHERE     (SENTENCE_RESTITUTION.AMOUNT IS NOT NULL) AND (SENTENCE_RESTITUTION.UPDATE_DATE BETWEEN DATEADD(month, - 2, GETDATE()) AND
                      GETDATE()) AND (CASE_CHARGE.CHARGE_STATE = 'CONVICTED')

-- Find all victim info for the probation/VRN/restitution:
SELECT     CASE_PERSON.CASE_ID_NBR, CASE_PERSON.PERSON_ID_NBR, CASE_PERSON.CASE_PERSON_TYPE, CASE_PERSON_INFO.LAST_NAME,
                      CASE_PERSON_INFO.FIRST_NAME, CASE_PERSON_INFO.MIDDLE_NAME, CASE_PERSON_ADDRESS.PREFIX, CASE_PERSON_ADDRESS.ADDRESS,
                      CASE_PERSON_ADDRESS.SUFFIX, CASE_PERSON_ADDRESS.UNIT, CASE_PERSON_ADDRESS.CITY, CASE_PERSON_ADDRESS.STATE,
                      CASE_PERSON_ADDRESS.ZIPCODE, CASE_PERSON_PHONE.AREA_CODE, CASE_PERSON_PHONE.PHONE, CASE_PERSON_PHONE.PHONE_EXT,
                      CASE_PERSON_ADDRESS.EMAIL
INTO            CFA_TOM_VICTIM_INFO
FROM         CASE_PERSON LEFT OUTER JOIN
                      CFA_TOM_VRN ON CASE_PERSON.CASE_ID_NBR = CFA_TOM_VRN.CASE_ID_NBR AND
                      CASE_PERSON.PERSON_ID_NBR = CFA_TOM_VRN.PERSON_ID_NBR LEFT OUTER JOIN
                      CFA_TOM_PROBATION ON CASE_PERSON.CASE_ID_NBR = CFA_TOM_PROBATION.CASE_ID_NBR LEFT OUTER JOIN
                      CFA_TOM_RESTITUTION ON CASE_PERSON.PERSON_ID_NBR = CFA_TOM_RESTITUTION.VICTIM_PERSON_ID_NBR AND
                      CASE_PERSON.CASE_ID_NBR = CFA_TOM_RESTITUTION.CASE_ID_NBR LEFT OUTER JOIN
                      CASE_PERSON_INFO LEFT OUTER JOIN
                      CASE_PERSON_ADDRESS ON CASE_PERSON_INFO.PERSON_ID_NBR = CASE_PERSON_ADDRESS.PERSON_ID_NBR
AND (CASE_PERSON_ADDRESS.SUB_ONLY = 'T') AND (CASE_PERSON_ADDRESS.ALL_DOCS = 'T') LEFT OUTER JOIN
                      CASE_PERSON_PHONE ON CASE_PERSON_INFO.PERSON_ID_NBR = CASE_PERSON_PHONE.PERSON_ID_NBR  AND
                      (CASE_PERSON_PHONE.DEFAULT_PHONE = 'T') ON
                      CASE_PERSON.PERSON_ID_NBR = CASE_PERSON_INFO.PERSON_ID_NBR
WHERE     (CASE_PERSON.CASE_PERSON_TYPE IN ('VIC/WIT', 'VICTIM')) AND (CFA_TOM_PROBATION.CASE_ID_NBR IS NOT NULL) OR
                      (CFA_TOM_RESTITUTION.CASE_ID_NBR IS NOT NULL) OR
                      (CFA_TOM_VRN.CASE_ID_NBR IS NOT NULL)


-- Find all Defendant info
SELECT     CASE_PERSON.CASE_ID_NBR, CASE_PERSON.PERSON_ID_NBR, CASE_PERSON.CASE_PERSON_TYPE, CASE_PERSON_INFO.LAST_NAME,
                      CASE_PERSON_INFO.FIRST_NAME, CASE_PERSON_INFO.MIDDLE_NAME, CASE_PERSON_INFO.DOB, CASE_PERSON_INFO.OREGON_SID_NBR,
                      PERSON.LAST_NAME AS DDA_LAST_NAME, PERSON.FIRST_NAME AS DDA_FIRST_NAME, CASE_PERSON.COURT_NBR
INTO            CFA_TOM_DEFENDANT_INFO
FROM         CASE_PERSON LEFT OUTER JOIN
                      CFA_TOM_RESTITUTION ON CASE_PERSON.PERSON_ID_NBR = CFA_TOM_RESTITUTION.OFFENDER_PERSON_ID_NBR AND
                      CASE_PERSON.CASE_ID_NBR = CFA_TOM_RESTITUTION.CASE_ID_NBR LEFT OUTER JOIN
                      PERSON ON CASE_PERSON.DA_CODE = PERSON.PERSON_CODE LEFT OUTER JOIN
                      CFA_TOM_VRN ON CASE_PERSON.CASE_ID_NBR = CFA_TOM_VRN.CASE_ID_NBR LEFT OUTER JOIN
                      CFA_TOM_PROBATION ON CASE_PERSON.CASE_ID_NBR = CFA_TOM_PROBATION.CASE_ID_NBR LEFT OUTER JOIN
                      CASE_PERSON_INFO ON CASE_PERSON.PERSON_ID_NBR = CASE_PERSON_INFO.PERSON_ID_NBR
WHERE     (CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT') AND (CFA_TOM_PROBATION.CASE_ID_NBR IS NOT NULL) OR
                      (CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT') AND (CFA_TOM_RESTITUTION.CASE_ID_NBR IS NOT NULL) OR
                      (CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT') AND (CFA_TOM_VRN.CASE_ID_NBR IS NOT NULL)
