SELECT CASE_ID_NBR, EVENT_TYPE, RESULT, MAX(UPDATE_DATE) AS UPDATE_DATE, PERSON_ID_NBR
INTO CFA_TOM_VRN
FROM  CASE_EVENT
WHERE (EVENT_TYPE LIKE 'VRN%')
  AND (CREATE_DATE BETWEEN DATEADD(month, -2, GETDATE()) AND GETDATE())
GROUP BY CASE_ID_NBR, EVENT_TYPE, RESULT, PERSON_ID_NBR
ORDER BY CASE_ID_NBR;

-- Delete Test Users
UPDATE        CFA_TOM_VRN
SET EVENT_TYPE = 'X'
FROM CFA_TOM_VRN
LEFT OUTER JOIN                      CASE_PERSON ON CFA_TOM_VRN.CASE_ID_NBR = CASE_PERSON.CASE_ID_NBR AND
                      CFA_TOM_VRN.PERSON_ID_NBR = CASE_PERSON.PERSON_ID_NBR
WHERE     (CASE_PERSON.ASSIGNED_COURT = 'TEST')

DELETE FROM CFA_TOM_VRN WHERE EVENT_TYPE = 'X';
