-- Find all Defendant info
SELECT     CASE_PERSON.CASE_ID_NBR, CASE_PERSON.PERSON_ID_NBR, CASE_PERSON.CASE_PERSON_TYPE, CASE_PERSON_INFO.LAST_NAME,
                      CASE_PERSON_INFO.FIRST_NAME, CASE_PERSON_INFO.MIDDLE_NAME, CASE_PERSON_INFO.DOB, CASE_PERSON_INFO.OREGON_SID_NBR,
                      PERSON.LAST_NAME AS DDA_LAST_NAME, PERSON.FIRST_NAME AS DDA_FIRST_NAME, CASE_PERSON.COURT_NBR AS COURT_CASE_NBR,
                      CASE_MAIN.CASE_NBR AS DA_CASE_NBR, CASE_PERSON_INFO.SEX
INTO            CFA_TOM_DEFENDANT_INFO
FROM         CASE_PERSON INNER JOIN
                      CASE_MAIN ON CASE_PERSON.CASE_ID_NBR = CASE_MAIN.CASE_ID_NBR INNER JOIN
                          (SELECT     CASE_ID_NBR
                            FROM          CFA_TOM_PROBATION
                            UNION
                            SELECT     CASE_ID_NBR
                            FROM         CFA_TOM_VRN
                            UNION
                            SELECT     CASE_ID_NBR
                            FROM         CFA_TOM_RESTITUTION) AS CASES ON CASES.CASE_ID_NBR = CASE_PERSON.CASE_ID_NBR LEFT OUTER JOIN
                      PERSON ON CASE_PERSON.DA_CODE = PERSON.PERSON_CODE LEFT OUTER JOIN
                      CASE_PERSON_INFO ON CASE_PERSON.PERSON_ID_NBR = CASE_PERSON_INFO.PERSON_ID_NBR
WHERE     (CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT')
