SELECT     CFA_TOM_VRN.CASE_ID_NBR, CFA_TOM_VRN.PERSON_ID_NBR, CODE_TABLE.TABLE_DESC AS RESULT_DESC,
                      CODE_TABLE_1.TABLE_DESC AS FLAG_DESC
FROM         CFA_TOM_VRN INNER JOIN
                      CODE_TABLE ON CFA_TOM_VRN.RESULT = CODE_TABLE.TABLE_CODE INNER JOIN
                      CASE_FLAG ON CFA_TOM_VRN.CASE_ID_NBR = CASE_FLAG.CASE_ID_NBR AND
                      CFA_TOM_VRN.PERSON_ID_NBR = CASE_FLAG.PERSON_ID_NBR INNER JOIN
                      CODE_TABLE AS CODE_TABLE_1 ON CASE_FLAG.FLAG_TYPE = CODE_TABLE_1.TABLE_CODE
WHERE     (CFA_TOM_VRN.UPDATE_DATE > '2017-07-14') AND (CFA_TOM_VRN.EVENT_TYPE IN ('VRN', 'VRNM'))
ORDER BY CFA_TOM_VRN.UPDATE_DATE DESC
