SELECT     CFA_TOM_VRN.CASE_ID_NBR, CFA_TOM_VRN.PERSON_ID_NBR, CODE_TABLE.TABLE_DESC AS FLAG_DESC
FROM         CFA_TOM_VRN INNER JOIN
                      CASE_FLAG ON CFA_TOM_VRN.CASE_ID_NBR = CASE_FLAG.CASE_ID_NBR AND
                      CFA_TOM_VRN.PERSON_ID_NBR = CASE_FLAG.PERSON_ID_NBR INNER JOIN
                      CODE_TABLE ON CASE_FLAG.FLAG_TYPE = CODE_TABLE.TABLE_CODE
