SELECT     CASE_MAIN.CASE_ID_NBR AS id, CASE_MAIN.CASE_NBR AS da_case_number, CASE_PERSON.COURT_NBR AS court_case_number, 
                      CASE_MAIN.FIRST_ADVOCATE_CODE AS advocate, PERSON.LAST_NAME AS prosecutor_last_name, 
                      PERSON.FIRST_NAME AS prosecutor_first_name
FROM         CASE_MAIN LEFT OUTER JOIN
                      CASE_PERSON ON CASE_MAIN.CASE_ID_NBR = CASE_PERSON.CASE_ID_NBR AND 
                      CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT' AND CASE_PERSON.CASE_PERSON_NBR = 1
		      INNER JOIN PERSON ON CASE_PERSON.DA_CODE = PERSON.PERSON_CODE
WHERE     (CASE_MAIN.UPDATE_DATE BETWEEN DATEADD(month, -2, GETDATE()) AND GETDATE())
GROUP BY CASE_MAIN.CASE_ID_NBR, CASE_MAIN.CASE_NBR, CASE_MAIN.FIRST_ADVOCATE_CODE, PERSON.LAST_NAME, PERSON.FIRST_NAME, 
                      CASE_PERSON.COURT_NBR
