SELECT     CASE_MAIN.CASE_ID_NBR AS id, CASE_MAIN.CASE_NBR AS da_case_number, CASE_MAIN.FIRST_ADVOCATE_CODE AS advocate, 
                      PERSON.LAST_NAME as prosecutor_last_name, PERSON.FIRST_NAME as prosecutor_first_name
FROM         CASE_MAIN INNER JOIN
                      CASE_PERSON ON CASE_MAIN.CASE_ID_NBR = CASE_PERSON.CASE_ID_NBR AND 
                      CASE_PERSON.CASE_PERSON_TYPE = 'DEFENDANT' INNER JOIN
                      PERSON ON CASE_PERSON.DA_CODE = PERSON.PERSON_CODE
WHERE     (CASE_MAIN.UPDATE_DATE BETWEEN DATEADD(month, -2, GETDATE()) AND GETDATE())
GROUP BY CASE_MAIN.CASE_ID_NBR, CASE_MAIN.CASE_NBR, CASE_MAIN.FIRST_ADVOCATE_CODE, PERSON.LAST_NAME, PERSON.FIRST_NAME
