---
- hosts: all
  gather_facts: false

  tasks:
  - name: Install python (for ansible itself)
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    become: true

  # 1. Create an "app" user and group which will have permissions necessary to
  # run the app
  - name: Create app group
    group:
      name: app
    become: true

  - name: Create user 'app'
    user:
      name: app
      group: app
      comment: "CaseCompanion Application"
    become: true

  # 2. Create a "tdooner" user with my SSH key
  - name: Create user 'tdooner'
    user:
      name: tdooner
      groups: app
      append: true
    become: true

  - name: Cache rbenv directory between builds
    file:
      src: "/mnt/cache/rbenv"
      dest: "/home/app/.rbenv"
      state: link
    when: packer_builder_type == "docker" and cache_rbenv_during_build == "true"

# 3. Install rbenv, ruby
- hosts: all
  gather_facts: true
  vars:
    rbenv:
      env: user
      version: 'v1.1.1'
      default_ruby: 2.4.0
      rubies:
        - version: 2.4.0
  roles:
    - role: zzet.rbenv
      rbenv_extra_depends:
        - ca-certificates
        - curl
        - git
      rbenv_users:
        - app

# 4. Install packages that are application dependencies
- hosts: all
  gather_facts: false
  tasks:
    - name: Install application dependencies
      apt:
        name: "{{ item }}"
      with_items:
        - postgresql-9.5 # TODO: Use RDS or a different instance?
        - libpq-dev
        - libsqlite3-dev
        - nodejs # a javascript runtime is required for uglifier
        - rsync # for copying
      become: true

    # 5. Create a systemd unit file for the application with an EnvironmentFile
    # set with the desired configuration. Enable the service to start on boot.
    - name: Install systemd template
      template:
        src: ./templates/casecompanion.service.j2
        dest: /etc/systemd/system/casecompanion.service
      become: true

    - name: Enable systemd service on boot
      file:
        src: /etc/systemd/system/casecompanion.service
        dest: /etc/systemd/system/multi-user.target.wants/casecompanion.service
        state: link
      become: true

# 6. Add application code and deploy folder structure
- hosts: all
  become: true
  become_user: app
  gather_facts: false
  vars:
    user: app
    home_directory: '/home/{{ user }}'
    deploy_to: '{{ home_directory }}'
    gem_home: '{{ home_directory }}/.rbenv/versions/2.4.0'
    rails_env: production
    bundle_install_options: "--gemfile='./Gemfile' --deployment"
    rails_bin_paths:
      - "{{ home_directory }}/.rbenv/shims"
    custom_environment:
      APP_DOMAIN: myadvocateoregon.org
  roles:
    - role: nicolai86.prepare-release
      repo: https://github.com/multnomah-fellowship/casecompanion.git
      branch: master
      templates:
        - { src: "./templates/env.j2", dest: '{{ shared_path }}/.env' }
      symlinks:
        # TODO: logging
        # TODO: Puma
        - { src: '{{ shared_path }}/vendor/bundle', dest: '{{ build_path }}/vendor/bundle' }
        - { src: '{{ shared_path }}/.env', dest: '{{ build_path }}/.env' }
        - { src: '{{ shared_path }}/config/database.yml', dest: '{{ build_path }}/config/database.yml' }
      directories:
        - '{{ shared_path }}/config'
        - '{{ shared_path }}/log'
        - '{{ shared_path }}/public'
      tags: deploy
    - role: ansible-rails-deployment
      migrate: no # TODO: this can't be done until postgres is running; figure out how to do it in an RDS world
      compile_assets: yes
      force_migrate: no
      force_asset_compilation: no
      tags: deploy
    - role: nicolai86.finalize-release
      tags: deploy

# 7. Install and configure nginx
- hosts: all
  become: true
  gather_facts: true
  roles:
    - role: jdauphant.nginx
      nginx_sites:
        casecompanion:
          template: ./templates/casecompanion.conf.j2

# 8. Figure out logging / log rotation. Maybe just use systemd.
