---
- hosts: all
  gather_facts: false

  tasks:
  - name: Install python (for ansible itself)
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  - name: Install sudo (for ansible itself)
    apt:
      name: sudo

  # This should probably use RDS instead of an on-instance database
  - name: Install postgresql
    apt:
      name: postgresql-9.5

  # 1. Create an "app" user and group which will have permissions necessary to
  # run the app
  - name: Create app group
    group:
      name: app

  - name: Create user 'app'
    user:
      name: app
      group: app
      comment: "CaseCompanion Application"

  # 2. Create a "tdooner" user with my SSH key
  - name: Create user 'tdooner'
    user:
      name: tdooner
      groups: app
      append: true

# 3. Install rbenv, ruby
- hosts: all
  gather_facts: true
  vars:
    rbenv:
      env: user
      version: 'v1.1.1'
      default_ruby: 2.4.0
      rubies:
        - version: 2.4.0

  roles:
    - role: zzet.rbenv
      rbenv_extra_depends:
        - ca-certificates
        - curl
      rbenv_users:
        - app

# 4. Create a systemd unit file for the application with an EnvironmentFile
#    set with the desired configuration. Enable the service to start on boot.
# 5. Add application code
# 6. Get nginx and puma going.
# 7. Figure out logging / log rotation. Maybe just use systemd.
# 8. Copy in the code and configuration for the deploy
